CREATE TABLE [_Copy Of dbo_ContactGeneral before updating csr] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [CompName] VARCHAR (80),
  [OperatingAs] VARCHAR (80),
  [NaicsCodeID] LONG ,
  [IsClient] BIT ,
  [IsVendor] BIT ,
  [IsCompetitor] BIT ,
  [IsCourier] BIT ,
  [Website] VARCHAR (255),
  [TrackSite] VARCHAR (255),
  [EmailDomain] VARCHAR (255),
  [SalesRepID] LONG ,
  [SalesMgrID] LONG ,
  [CsrID] LONG ,
  [APContactID] LONG ,
  [ARContactID] LONG ,
  [ClientSince] VARCHAR (10),
  [LastInvoice] VARCHAR (10),
  [LastEstimate] VARCHAR (10),
  [LastDocket] VARCHAR (10),
  [CreditOrderOK] BIT ,
  [CreditShipOK] BIT ,
  [Notes] LONGTEXT ,
  [SendEmail] BIT ,
  [SendMail] BIT ,
  [LastEdited] DATETIME ,
  [LastEditedBy] LONG ,
  [SendInvoiceViaEmail] BIT ,
  [SendInvoiceViaSnailMail] BIT ,
  [SendInvoiceViaFax] BIT ,
  [SendPOViaEmail] BIT ,
  [SendPOViaFax] BIT ,
  [PORequired] BIT ,
  [GSTExempt] BIT ,
  [Verified] BIT ,
  [VerifiedBy] LONG ,
  [VerifiedOn] DATETIME 
)
