CREATE TABLE [_FromClaude1] (
  [ID1] AUTOINCREMENT CONSTRAINT [ID1] PRIMARY KEY  UNIQUE  NOT NULL ,
  [ID] DOUBLE ,
  [Employee_ID] VARCHAR (255),
  [CompanyName] VARCHAR (255),
  [Department] VARCHAR (255),
  [ContactName] VARCHAR (255),
  [ContactTitle] VARCHAR (255),
  [NewClient] BIT ,
  [NewClientDate] VARCHAR (255),
  [Reps_ID (ignore)] DOUBLE ,
  [AssignedSalesRep] VARCHAR (255),
  [AxisMISEmployeeID] LONG ,
  [Angie] VARCHAR (255),
  [Field12] VARCHAR (255),
  [Carmen] VARCHAR (255),
  [Cheryl] VARCHAR (255),
  [Dale] VARCHAR (255),
  [Dan] VARCHAR (255),
  [Dar] VARCHAR (255),
  [Lin] VARCHAR (255),
  [Tammy] VARCHAR (255),
  [Add] VARCHAR (255),
  [Add2] VARCHAR (255),
  [City] VARCHAR (255),
  [Prov] VARCHAR (255),
  [PC] VARCHAR (255),
  [Phone] VARCHAR (255)
)
