CREATE TABLE [Copy Of dbo_ContactName] (
  [ID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [IsActive] BIT ,
  [ContactGeneralID] LONG ,
  [ContactLocationID] LONG ,
  [Prefix] VARCHAR (20),
  [FN] VARCHAR (50),
  [MN] VARCHAR (50),
  [LN] VARCHAR (50),
  [Suffix] VARCHAR (20),
  [PreferredName] VARCHAR (50),
  [Title] VARCHAR (100),
  [Department] VARCHAR (50),
  [PhDirect] VARCHAR (20),
  [PhExt] VARCHAR (20),
  [PhFax] VARCHAR (20),
  [PhMobile] VARCHAR (20),
  [PhRes] VARCHAR (20),
  [Birthday] DATETIME ,
  [Anniversary] DATETIME ,
  [WithCompanySince] VARCHAR (10),
  [Gender] VARCHAR (1),
  [Email] VARCHAR (100),
  [SpName] VARCHAR (50),
  [SpBirthday] DATETIME ,
  [ChName] LONGTEXT ,
  [EmailRes] VARCHAR (100),
  [Notes] LONGTEXT ,
  [ResAdd1] VARCHAR (80),
  [ResAdd2] VARCHAR (80),
  [ResCity] VARCHAR (50),
  [ResProv] VARCHAR (2),
  [ResPC] VARCHAR (10),
  [ResCountry] VARCHAR (20),
  [SendEmail] BIT ,
  [SendMail] BIT ,
  [LastEdited] DATETIME ,
  [LastEditedBy] LONG ,
  [Verified] BIT ,
  [VerifiedBy] LONG ,
  [VerifiedOn] DATETIME 
)
