CREATE TABLE [dboC8000Log] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY  UNIQUE  NOT NULL ,
  [Timestamp Done Printing] DATETIME ,
  [Job Title] VARCHAR (255),
  [Print Status] VARCHAR (255),
  [User] VARCHAR (255),
  [Size] LONG ,
  [Pages] LONG ,
  [Number Of Copies Of Job Printed] LONG ,
  [Total Number Of Sheets Printed] LONG ,
  [Total Number Of Black And White Pages Printed] LONG ,
  [Total Number Of Color Pages Printed] LONG ,
  [Media Size] VARCHAR (255),
  [Media Type] VARCHAR (255),
  [Media Weight] VARCHAR (255),
  [Paper Source] VARCHAR (255),
  [Date/Time] VARCHAR (255),
  [Rip Error] VARCHAR (255),
  [Timestamp Spooling] DATETIME ,
  [Timestamp Done Spooling] DATETIME ,
  [Timestamp Waiting To Rip] DATETIME ,
  [Timestamp Ripping] DATETIME ,
  [Timestamp Done Ripping] DATETIME ,
  [Process Time] VARCHAR (255),
  [Timestamp Waiting To Print] DATETIME ,
  [Timestamp Printing] DATETIME ,
  [Submitted By] VARCHAR (255),
  [Authorized User] VARCHAR (255),
  [Device/Group] VARCHAR (255),
  [Server] VARCHAR (255),
  [Virtual Printer] VARCHAR (255),
  [Instructions] VARCHAR (255),
  [Notes1] VARCHAR (255),
  [Notes2] VARCHAR (255),
  [Paper Catalog Name] VARCHAR (255),
  [Printed By] VARCHAR (255),
  [Interpreter] VARCHAR (255),
  [PDL] VARCHAR (255),
  [Number of Rips Present] LONG ,
  [Number of Rips Used] LONG ,
  [Sheets] LONG ,
  [Product ID] VARCHAR (255),
  [Number Of Pages Printed] LONG ,
  [Total Number Of Sample Pages Printed] LONG ,
  [Total Number Of Tab Pages Printed] LONG 
)
