CREATE TABLE [pdqLayout] (
  [QuoteID] VARCHAR (255),
  [ImpositionID] VARCHAR (255),
  [SectionName] VARCHAR (255),
  [NumberOfSheetTypes] VARCHAR (255),
  [PrintMethod] VARCHAR (255),
  [NumberOfBlocks] VARCHAR (255),
  [WastedBlocks] VARCHAR (255),
  [KindsOnPage] VARCHAR (255),
  [Orientation] VARCHAR (255),
  [numberUp] VARCHAR (255),
  [blockMultiplierCancel] VARCHAR (255),
  [kindsOnThisPage] VARCHAR (255),
  [X] VARCHAR (255),
  [Y] VARCHAR (255),
  [FoldX] VARCHAR (255),
  [FoldY] VARCHAR (255),
  [Stonehenging] VARCHAR (255),
  [Plates] VARCHAR (255),
  [MasterSheets] VARCHAR (255),
  [NumberOutMaster] VARCHAR (255),
  [GrossSheets] VARCHAR (255),
  [NetSheets] VARCHAR (255)
)
