CREATE TABLE [pdqSection] (
  [QuoteID] VARCHAR (255),
  [Name] VARCHAR (255),
  [Type] VARCHAR (255),
  [Pages] VARCHAR (255),
  [SizeX] VARCHAR (255),
  [SizeXInch] DOUBLE ,
  [SizeY] VARCHAR (255),
  [SizeYInch] DOUBLE ,
  [Orientation] VARCHAR (255),
  [Kinds] VARCHAR (255),
  [SortRatios] VARCHAR (255),
  [lbs] VARCHAR (255),
  [LbsCover] LONG ,
  [LbsText] LONG ,
  [FlapX] VARCHAR (255),
  [FlapXInch] DOUBLE ,
  [FlapY] VARCHAR (255),
  [FlapYInch] DOUBLE ,
  [MachineSealed] VARCHAR (255),
  [PlatesRequired] VARCHAR (255),
  [Imposition] VARCHAR (255),
  [FoldX] VARCHAR (255),
  [FoldY] VARCHAR (255),
  [FoldXInch] DOUBLE ,
  [FoldYInch] DOUBLE 
)
